name: qr_attendance_system
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11 # Needed for mobile and desktop platforms
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.1
  path: ^1.9.0
  logger: ^2.5.0
  qr_code_scanner: ^0.4.0
  qr_flutter: ^4.0.0
  crypto: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_core: ^3.8.1
  provider: ^6.1.2
  sqflite_common_ffi: ^2.2.2
  hive_generator: ^1.1.3
  build_runner: ^2.3.3
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true